version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: project
      MYSQL_USER: shubham
      MYSQL_PASSWORD: shubham
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - "~/DOCKER/MYSQL:/docker-entrypoint-initdb.d"
    networks:
      - lamp-docker
  www:
    depends_on:
      - db
    image: myphp:latest
    build:
      context: .
      dockerfile: ./dockerfile
    volumes:
      - "./:/var/www/html"
    ports:
      - 80:80
      - 443:443
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge
